### ISSUE TITLE
Latest release doesn't ship __version__

### ISSUE THREAD

**Issue by jtilly** [conda-forge/lightgbm-feedstock#66]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

Since the merge of #65, this fails:

```
>>> from lightgbm import __version__
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    from lightgbm import __version__
ImportError: cannot import name '__version__' from 'lightgbm' (/private/tmp/lgb/lib/python3.13/site-packages/lightgbm/__init__.py)
``` 

Also, I don't think I can install "yesterday's version", because https://github.com/conda-forge/lightgbm-feedstock/pull/65 didn't bump the build number.

### Installed packages

List of packages in environment: "/private/tmp/lgb"

  Name                       Version     Build                 Channel    
────────────────────────────────────────────────────────────────────────────
  bzip2                      1.0.8       h99b78c6_7            conda-forge
  ca-certificates            2024.8.30   hf0a4a13_0            conda-forge
  icu                        75.1        hfee45f7_0            conda-forge
  khronos-opencl-icd-loader  2024.05.08  hd74edd7_0            conda-forge
  libblas                    3.9.0       24_osxarm64_openblas  conda-forge
  libboost                   1.84.0      h29978a0_6            conda-forge
  libcblas                   3.9.0       24_osxarm64_openblas  conda-forge
  libcxx                     19.1.1      ha82da77_0            conda-forge
  libexpat                   2.6.3       hf9b8971_0            conda-forge
  libffi                     3.4.2       h3422bc3_5            conda-forge
  libgfortran                5.0.0       13_2_0_hd922786_3     conda-forge
  libgfortran5               13.2.0      hf226fd6_3            conda-forge
  liblapack                  3.9.0       24_osxarm64_openblas  conda-forge
  liblightgbm                4.5.0       cpu_h7ba702d_2        conda-forge
  libmpdec                   4.0.0       h99b78c6_0            conda-forge
  libopenblas                0.3.27      openmp_h517c56d_1     conda-forge
  libsqlite                  3.46.1      hc14010f_0            conda-forge
  libzlib                    1.3.1       h8359307_2            conda-forge
  lightgbm                   4.5.0       cpu_py_2              conda-forge
  llvm-openmp                19.1.1      h6cdba0f_0            conda-forge
  ncurses                    6.5         h7bae524_1            conda-forge
  numpy                      2.1.2       py313hab0c69d_0       conda-forge
  openssl                    3.3.2       h8359307_0            conda-forge
  pip                        24.2        pyh145f28c_1          conda-forge
  python                     3.13.0      h206b6c5_100_cp313    conda-forge
  python_abi                 3.13        5_cp313               conda-forge
  readline                   8.2         h92ec313_1            conda-forge
  scipy                      1.14.1      py313h5ce5e94_0       conda-forge
  tk                         8.6.13      h5083fa2_1            conda-forge
  tzdata                     2024b       hc8b5060_0            conda-forge
  xz                         5.2.6       h57fd34a_0            conda-forge
  zstd                       1.5.6       hb46c0d2_0            conda-forge

### Environment info

standard

**Comment by jtilly** [comment]
Just to give some context:

`lightgbm` sets `__version__` based on a file `VERSION.txt`.

https://github.com/microsoft/LightGBM/blob/7eae66a7bd0cf5e4bb081f23b61ad11b4f66d706/python-package/lightgbm/__init__.py#L29-L31

This file is missing from the conda package after the split:

```
.
├── info
│   ├── about.json
│   ├── files
│   ├── git
│   ├── hash_input.json
│   ├── index.json
│   ├── licenses
│   │   └── LICENSE
│   ├── link.json
│   ├── paths.json
│   ├── recipe
│   │   ├── conda_build_config.yaml
│   │   ├── install-python.sh
│   │   ├── meta.yaml
│   │   └── parent
│   │       ├── bld.bat
│   │       ├── boost_shared.diff
│   │       ├── build.sh
│   │       ├── install-python.bat
│   │       ├── install-python.sh
│   │       ├── meta.yaml
│   │       ├── python_run_test.py
│   │       ├── recipe-scripts-license.txt
│   │       └── use_precompiled.diff
│   └── test
│       ├── python_run_test.py
│       ├── run_test.bat
│       ├── run_test.py
│       ├── run_test.sh
│       └── test_time_dependencies.json
└── site-packages
    ├── lightgbm
    │   ├── __init__.py
    │   ├── basic.py
    │   ├── callback.py
    │   ├── compat.py
    │   ├── dask.py
    │   ├── engine.py
    │   ├── libpath.py
    │   ├── plotting.py
    │   ├── py.typed
    │   └── sklearn.py
    └── lightgbm-4.5.0.dist-info
        ├── INSTALLER
        ├── LICENSE
        ├── METADATA
        ├── RECORD
        ├── REQUESTED
        ├── WHEEL
        ├── direct_url.json
        └── top_level.txt
```
